boost-ext/sml

doc/index.md, doc/overview.md, doc/tutorial.md
just some cleaning while reading docs/sources
=> a pair of document/comment examples fixes

include/boost/msm-lite.hpp, test/ft.cpp
* Added a `process_internal_event` / `process_event_impl` variation that takes a `current_state`  parameter and only executes the dispatch table for that state (i.e. region).
* Used this for the `on_exit` / `on_entry` internal events via an overload of `process_internal_event`, so that those events are only executed on the expected region.
* Added simple test case, which fails without this fix and passes with it.
=> Fix orthogonal region entry / exit events to trigger only on expected region

include/boost/msm-lite.hpp, test/ft_thread.cpp
* Switched from `std::mutex` to `std::recursive_mutex` to avoid deadlock when `process_event` is called during another `process_event` call.
* Added a test case showing the issue.  Unfortunately the test case is rather harsh, since without the fix the test executable just hangs forever ;)
* In #61 it was mentioned that eventually the mutex type will be configurable, but for now this solves the immediate problem.
=> Fix reentrant deadlock

Makefile, include/boost/msm-lite.hpp, test/ft_logging.cpp
* Currently, `""_t` events have a `c_str` method, and user defined
events can be defined to have a `c_str` method, but internal events do
not have a `c_str` method. This omission means you cannot use `c_str`
when logging events.
* Also, `""_s` states and the special "terminate" state support `c_str`.
But user-defined `c_str` members are not used when logging states -
`__PRETTY_FUNCTION__` is always used.
* So add `c_str` function to `internal_event`s and derivatives, so that
all events can be assumed to have a `c_str` function when logging
(assuming the user defines their custom events with a `c_str` method).
* Also add support for `c_str` function within state types via a
`stringable` concept.
* Added a test case for logging of events, internal events, and states.
The `stringable` …
=> Add support for `c_str()` in user defined events and state types

include/boost/sml.hpp, include/boost/sml/front/actions/defer.hpp
Moved from defer_event no longer call the destructor of T.
This fix assumes that id '-1' is never used as a valid id.
=> Fixed #89.

include/boost/sml.hpp, include/boost/sml/front/operators.hpp
Logging of guards and actions was missing if guards/actions were called
that take additional parameters (e.g. the current event).
This is fixed now.
This fixes #104 .
=> [front-end] Fix #104 Logging of guards and actions.

include/boost/sml.hpp, include/boost/sml/front/operators.hpp
Logical expressions of guards are now handled as expected and known from
C++:
* In AND logical expressions, the first guard that returns false
prevents the remaining guards from being executed.
* In OR logical expressions, the first guard that returns true prevents
the remaining guards from being executed.
This fixes #97 .
=> [front-end] Fix #97 Guards and logical expressions.

include/boost/sml.hpp, include/boost/sml/aux_/type_traits.hpp
With C++17 `noexcept` becomes part of a function's signature (if present).
Therefore, template-specializations which try to match a function signature must also consider the 'noexcept' keyword now.
This fixes #107.
=> Fix #107. Add support for C++17 noexcept.

include/boost/sml/utility/dispatch_table.hpp, test/ft/dispatch_table.cpp
In the past we cannot define a dispatch table such as following:
```
auto dispatch_event =
sml::utility::make_dispatch_table<OperationalLogic::emptyEvent, 0 /*min*/,
20 /*max*/, StateMachine>(sm);
```
where StateMachine have rebind policies, such as:
```
sml::sm<logging, sml::logger<my_logger>> sm{logger};
```
It is because the dispatch table only allow the SM have one template input.
This patch is going to let SM with rebind_policies could have dispatch table
=> make dispatch table could add SM with rebind_policies

include/boost/sml.hpp, include/boost/sml/front/actions/process.hpp, include/boost/sml/front/operators.hpp, test/ft/actions_process.cpp
Events dispatched from a substate-machine were only processed within that substate-machine and not in the parent state-machines.
This is fixed now!
Events dispatched from a substate-machine are now processed by the entire state-machine and no longer only in the substate-machine.
If called via `process( event{} )` directly from the transition-table or from within an action via `sm.process_event( event{} )` makes no difference.
---
Note, however, that this fix requires the following observation to always be true:
* `TSubs` always contains all state-machines, the root-SM as well as all sub-SMs.
* The first entry in `TSubs` is always the root-SM.
I assume, this is always the case but maybe someone knows an obscure situation in which this is not true. Then please speak up!
This fixes #76 .
=> [front-end] Fix #76 Process event at root-SM if dispatched from sub-SM.

Makefile, include/boost/sml.hpp, include/boost/sml/aux_/type_traits.hpp, include/boost/sml/back/state_machine.hpp, test/ft/actions_process.cpp, test/ft/dispatch_table.cpp, tools/pph.sh
Fixed several warnings concerning *GCC*, *Clang* and *MSVC* that were treated as errors by the `Makefile`.
Note, however, that *MSVC* probably still cannot compile the code due to some other errors. (See continuous-integration results of *Appveyor*.)
Compiling the *SDL2* example with *GCC* still fails, because I was unable to fix (or even locate) the following warning which is treated as an error:
```
g++-6 example/sdl2.cpp -std=c++1y -Wall -Wextra -Werror -pedantic -pedantic-errors -I include -I . -o example/sdl2.out &&  example/sdl2.out
In file included from example/sdl2.cpp:8:0:
include/boost/sml.hpp: In instantiation of ‘struct boost::sml::v1_1_0::back::sm_impl<boost::sml::v1_1_0::back::sm_policy<sdl2> >::mappings’:
include/boost/sml.hpp:911:63:   required by substitution of …
```
=> Fixed several warnings (which were treated as errors).

include/boost/sml.hpp, include/boost/sml/aux_/type_traits.hpp
Older compiles might partially support C++17 but not support that `noexcept` became part of the type-system.
To prevent compiler-errors with these compilers an additional feature-test for that feature guards the additional type_traits which use that feature.
This fixes #126 .
=> [C++17] Additional feature-test to prevent compiler-errors.

include/boost/sml.hpp, include/boost/sml/back/mappings.hpp, test/ft/transitions.cpp
Now, it is possible to create a transition-table that has multiple transitions that match any event (via `event<_>`) but still can use guards and actions to distinguish between them.
**Note 1:** However, the events that should be matched by such transitions still must be used (verbatim) in some other (possibly unreachable) transition of the transition-table or they would be considered as *'unexpected'* events and not being considered by such *"catch-all"* transitions. (See issue #88.)
**Note 2:** If two transitions exist for a source-state that might match event `e1`, one directly using `event<e1>`, the other using `event<_>`, the translation with the more-specific form is always a better match, regardless of the order in which they appear in the transition-table.
For example, the …
=> Fix #110. Transitions with event<_> no longer ignore guards and actions.

include/boost/sml.hpp
__has_builtin macro was giving redefined warning when compiling SML with GCC.
=> Fixing "__has_builtin" redefined warning in GNUC

example/sdl2.cpp
Compilation of `example/sdl2.cpp` fails due to warnings being interpreted as errors.
This pull-request fixes that particular warning.
The rational behind it can be found in #135.
Fixes #135.
=> example/SDL2: Remove warning (which is interpreted as error).

doc/tutorial.md
Problem:
- The documentation for creating an event on the fly contains a typo,
which causes confusion on the part of new users.
Solution:
- Correct the typo.
=> :books: Correct on-the-fly event creation documentation

include/boost/sml.hpp, include/boost/sml/back/state_machine.hpp
Problem:
- Clang complains that the default ctor is explicit when used with array{}.
Solution:
- Add specialization for the default ctor which is not explicit.
=> :bug: State machine ctor without parameters shouldn't be explicit

.travis.yml, include/boost/sml.hpp, include/boost/sml/aux_/type_traits.hpp, include/boost/sml/aux_/utility.hpp, include/boost/sml/back/policies.hpp, include/boost/sml/back/state_machine.hpp, include/boost/sml/back/utility.hpp, include/boost/sml/front/state.hpp, include/boost/sml/state_machine.hpp, test/ft/actions_defer.cpp, test/ft/actions_process.cpp, test/ft/composite.cpp, test/ft/dependencies.cpp, test/ft/history.cpp, test/ft/orthogonal_regions.cpp, test/ft/policies_testing.cpp, test/ft/policies_thread_safe.cpp, test/ft/state_machine.cpp, test/ft/states.cpp, test/ft/transitions.cpp, test/ft/unexpected_events.cpp, test/ut/type_traits.cpp, test/ut/utility.cpp
Problem:
- DI implementation is overcomplicated in the pool.
Solution:
- Simplify it by doing the work in try_get instead.
=> :new: :art: Simplify dependency injection

include/boost/sml.hpp, include/boost/sml/back/policies.hpp, include/boost/sml/back/policies/thread_safety.hpp, include/boost/sml/back/state_machine.hpp
Problem:
- Policies are coupled to the SM.
Solution:
- Extract policies implementation into the policy itself.
=> :art: [back-end][policies] Refactor thread safe policy

include/boost/sml.hpp, include/boost/sml/back/policies.hpp
Problem:
- Dispatch optimizations depend on the compiler.
Solution:
- Apply defualt dispatch policy per compiler.
=> :racehorse: Default dispatch policy

include/boost/sml.hpp, include/boost/sml/back/policies/dispatch.hpp
Problem:
- GCC-6 with C++17 doesn't support auto template parameters.
Solution:
- Use int instead as it's for index_sequence.
=> :bug: Fix #177 - Can't compile with GCC 6

include/boost/sml.hpp, test/ft/state_machine.cpp
I'm not very happy with the semantics (current move ctor actually copies and this move assignment does the same) however this makes e.g. SM reset much cleaner (by assignment a fresh instance).
=> sm move assignment operator

Makefile, include/boost/sml.hpp, include/boost/sml/back/state_machine.hpp, include/boost/sml/transition_table.hpp, test/ft/CMakeLists.txt, test/ft/constexpr.cpp, test/ft/sizeof.cpp
Fixes fuchsia-statically-constructed-objects warning in clang-tidy when doing something like this:
```c++
constexpr auto my_state = boost::sml::event<class MyState>;
using namespace boost::sml;
constexpr auto my_event = "event1"_e;
```
Tested on clang and gcc only.
=> Add constexpr for event and state

CMakeLists.txt
This makes possible to use the library as cmake external project
(instead of [manually downloading the header](http://boost-experimental.github.io/sml/overview/index.html#quick-start))
* `CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.12)
project(test)
include(ExternalProject)
ExternalProject_Add(external_boost_sml
PREFIX "${CMAKE_BINARY_DIR}/external-projects"
GIT_REPOSITORY "https://github.com/arteniioleg/sml.git"
GIT_TAG "master"
CMAKE_ARGS
-DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/external-projects/installed
-DBUILD_BENCHMARKS=OFF
-DBUILD_DOCS=OFF
-DBUILD_EXAMPLES=OFF
-DBUILD_TESTS=OFF
)
set_target_properties(external_boost_sml PROPERTIES EXCLUDE_FROM_ALL TRUE)
add_executable(${PROJECT_NAME} main.cpp)
add_dependencies(${PROJECT_NAME} external_boost_sml) # comment to …
```
=> cmake: install headers and added options to disable targets build

include/boost/sml.hpp, include/boost/sml/transition_table.hpp
Problem:
- It's a standard practice to place User Defined Literals (UDLs) in an inline namespace literals, to allow users to opt in to the UDLs without using namespace full_library.
Solution:
- Place UDLs in `literals` inline namespace.
=> :new: :art: :bug: Fix #219 Place UDLs in an inline namespace

include/boost/sml.hpp, include/boost/sml/back/state_machine.hpp, include/boost/sml/back/transitions.hpp, include/boost/sml/front/transition.hpp, test/ft/transition_table.cpp, test/ft/transitions.cpp
Problem:
- Anonymous transitions after the first one are not processed.
Solution:
- Process them until there is nothing to do.
=> :bug: Process all anonymous transitions

doc/embo-2018/index.html, example/defer_and_process.cpp, include/boost/sml.hpp, include/boost/sml/back/internals.hpp, include/boost/sml/back/policies.hpp, include/boost/sml/back/policies/defer_queue.hpp, include/boost/sml/back/queue_handler.hpp, include/boost/sml/back/state_machine.hpp, include/boost/sml/front/actions/defer.hpp, test/ft/actions_defer.cpp
Remain the deferred event that from deferred_queue during the transition
process. Then, process the next deferred event. The event position is
not front(), so `std::queue` concept doesn't satisfies it. I need
iteration concept something like `std::deque`.
In order to do that, I introduced two flags that are `defer_processing_`
and `defer_again_`. In addition, to iterate deferred deque, two
iterators `defer_it_` and `defer_end_` are introduced.
=> Fixed #230.

.appveyor.yml, .travis.yml, include/boost/sml.hpp, include/boost/sml/back/state_machine.hpp, include/boost/sml/front/actions/defer.hpp, include/boost/sml/front/transition.hpp, include/boost/sml/transition_table.hpp, test/ft/transitions.cpp
Problem:
- travis is missing clang5/clang6/clang7 compilers.
- appveyor is missing MSVC 2017 Preview compiler.
Solution:
- Update travis.yml and appveyor.yml with the newest versions of available compilers.
=> :wrench: :arrow_up: [travis/appveyor] Update compilers

CMakeLists.txt
Problem:
- SML requires C++14 but still checks for whether a compiler supports
`-std=c++11` compiler flag.
Solution:
- Remove unused CMake check and variable for detecting C++11 support.
=> Remove unused cmake variable for C++11 support

CMakeLists.txt
Problem:
- We conditionally apply two compiler flags if the GCC min verson is
4.7.0 or later. This conditional is unneeded since SML only supports
GCC6 or later.
Solution:
- Remove the conditional check based on GCC version.
- Replace the compiler flags into the required set of compiler flags
applied via `target_compile_options`.
=> Simplify setting -ftrack-macro-expansion=0

test/unit/CMakeLists.txt
Problem:
- `test_unit` executable compiles `unit2.cpp` twice.
Solution:
- Only compile it once.
=> Remove compiling test cpp file twice

include/boost/sml.hpp, include/boost/sml/back/state_machine.hpp, test/ft/CMakeLists.txt, test/ft/actions_defer.cpp, test/ft/actions_process.cpp, test/ft/actions_process_n_defer.cpp
Hello again :)
This pull request address the issue raised in #243, that internal events are not processed after a queued events. The example given there is a simple queuing of an event, which when processed should fire an internal event. I added the example as a test, and three variants of the example that are more complicated.
The modification in the code is to loop on internal, deferred, and queued events, until a stable state is found - i.e. no more internal, deferred, or queued events. This happens in both the start and process_event methods. The way to achieve this was to make the queue processing function return a boolean, instead of being void. This fits with process_internal_events already returning a boolean, and also being looped on.
=> Loop on internal, deferred and queued events, until stable state found

include/boost/sml.hpp, include/boost/sml/back/utility.hpp, test/ft/composite.cpp
If a submachine appears only as a destination state of a transition, then its on_entry isn't called. This is issue #263 .
This is fixed by making sure that `get_sub_internal_events` returns the internal events aggregated from both source states and destination states of all submachines' transitions.
A test was added in `test/ft/composite.cpp`.
=> fixed: submachine internal events aren't called if only dst

include/boost/sml.hpp
- clang on Windows also sets the _MSC_VER flag
- to compile with msvc on Windows we need to check for _MSC_VER and !__clang__
- to compile with clang on Windows we need to check for __clang__
=> Fixing compiling on Windows using clang

include/boost/sml.hpp
We should cleanup this flag 0ba428d so that it does not leak outside the sml.hpp file
=> Undefine COMPILING_WITH_MSVC flag

doc/CHANGELOG.md, doc/tutorial.md
* Removes duplicate contributor
* Updates the tutorial logger to be equivalent to the one from the example code because it is confusing to see two different logger implementations.
=> Enhance documentation

include/boost/sml.hpp, include/boost/sml/back/state_machine.hpp, test/ft/actions_defer.cpp, test/ft/transitions.cpp
I'm on a short weekend roll :)
This pull request is about issue #294. The code in the issue was turned into a test, and also an analogous `on_exit` test.
The issue is about the matching of events. Before the fix, sml would give priority to any matching non-generic event - even if it was in an unrelated transition. But then these events would be discarded, exactly because they don't appear in the relevant transition.
The fix adds the possibility of matching the generic event in this case, exactly when the matched non-generic event isn't handled.
If it is handled, then it must have been relevant - so we don't need to try to match the generic event.
=> Fix non-trivial on_entry matching

include/boost/sml.hpp, include/boost/sml/back/state_machine.hpp, test/ft/actions_process.cpp
The document https://boost-experimental.github.io/sml/user_guide.html
said as follows:
```cpp
template<class T> requires configurable<T>
class sm {
public:
template<class TEvent> // no requirements
bool process_event(const TEvent&)
```
`process_event()` returns true when handled, false otherwise.
=> Fix process_event() return type from void to bool.

include/boost/sml.hpp, include/boost/sml/back/state_machine.hpp
Static code analysis has shown that the non-static class member defer_again_
is not inititialized in the constructor nor in any function that it calls.
=> Initialize defer_again_ member with  defer_flag_t default value

.travis.yml
Problem:
- `GCC/Clang/AppleClang` compilers are out of date.
Solution:
- Add GCC-8/GCC-9/Clang-9 and xcode images 11.
=> :wrench: [travis] Update `GCC/Clang/AppleClang` compilers

example/CMakeLists.txt, example/visitor.cpp, include/boost/sml.hpp, include/boost/sml/aux_/utility.hpp, include/boost/sml/back/policies/testing.hpp, include/boost/sml/transition_table.hpp
Problem:
- There is no example showig how to print state names using a visitor.
- There is no easy support to print sub State Machines state names.
Solution:
- Add example to print state names using a custom visitor and a composite State Machine.
=> :new: [example] State names visitor

example/actions_guards.cpp, include/boost/sml.hpp, include/boost/sml/aux_/utility.hpp, include/boost/sml/concepts/callable.hpp, test/ft/transition_table.cpp
Problem:
- Only lambda-expression like guards/actions are supported.
Solution:
- Add support for member-function like guards/actions using
`&type::member_function` syntax.
=> :new: [core] Support for member-function like guards/actions

Makefile
Problem:
- Modern theme is incorrectly called ext.
Solution:
- Change it to modern.
=> :bug: :books: [doc] Fix for `modern theme` generation

doc/tutorial.md
Problem:
- Link to the workshop is broken.
Solution:
- Update it using `https`.
=> :books: [doc] Fix workshop link

include/boost/sml.hpp, include/boost/sml/aux_/utility.hpp, include/boost/sml/back/state_machine.hpp, test/ft/CMakeLists.txt, test/ft/deep_sm.cpp
SML RAM usage and template depth during compilation can be reduced by doing small optimization on type declaration.
Optimization done here :
- Small optimization on unique_t impl
- Early calculation of unique events list in sm_impl. (This greatly reduce template depth)
The problems were linked to state machine with some depth since problem grow exponentially with depth.  
Test case do not cover deep SM.
=> Reduce compilation RAM usage

include/boost/sml.hpp, include/boost/sml/concepts/callable.hpp, test/ut/concepts.cpp
Problem:
- The `callable` concept currently does not recognize `noexcept` member functions
Solution:
- Add template specializations for `noexcept` member functions
=> Make callable concept recognize noexcept member functions

.travis.yml, example/data.cpp, example/dispatch_table.cpp, example/sdl2.cpp, include/boost/sml.hpp, include/boost/sml/back/state_machine.hpp, include/boost/sml/concepts/callable.hpp, include/boost/sml/transition_table.hpp, test/ft/deep_sm.cpp, test/ft/dispatch_table.cpp, test/ut/concepts.cpp
Problem:
- clang-format is out of date and `sml.hpp` is not in sync.
Solution:
- Add `__pph__` to define definition and call `tools/pph.sh` with clang-format.
=> :art: [style] Regenerate style and `sml.hpp`

example/actions_guards.cpp, include/boost/sml.hpp, include/boost/sml/aux_/utility.hpp
Problem:
- `noexcept` member function pointers are not accepted by `zero_wrapper`
Solution:
- Add specializations for `noexcept` member function pointers
=> Add `noexcept` template specializations for `zero_wrapper`

test/ft/transitions.cpp
Problem:
- Style is not regenerated for all files.
Solution:
- Execute `make style` to run clang-format-8 on all files.
=> :wrench: [clang-format] Regenerate style

example/CMakeLists.txt, example/in_place.cpp, include/boost/sml.hpp, include/boost/sml/back/state_machine.hpp, include/boost/sml/state_machine.hpp
Problem:
- CTAD can be used to define State Machines in-place.
Solution:
- Use struct instead of alias to support CTAD construction.
- Add example how to use `CTAD` with `sm`
Example:
```
sml::sm sm = [] {
using namespace sml;
return make_transition_table(...);
};
```
@
=> :new: [core] Support for `CTAD` with `sm`

example/actions_guards.cpp, test/ft/actions_process_n_defer.cpp
Problem:
- All files are required to have LICENSE info.
Solution:
- Add LICENSE to the top missing files.
=> :arrow_up: [copyright] Add  missing LICENSE info

doc/tutorial.md
Problem:
- Copy pasted the code and didn't compile! :)
Solution:
- Swapped a and r
Issue: #
Reviewers:
@
=> Fix typo in tutorial.md

include/boost/sml.hpp, include/boost/sml/aux_/utility.hpp, test/ft/state_machine.cpp
Problem:
- non-copyable deps can't be passed via reference anymore.
Solution:
- Ensure that non-copyable deps can't be injected and won't be copied by the pool.
=> :bug: non-copyable dependencies fail to compile, Fix #464

Makefile, example/plant_uml.cpp, include/boost/sml/aux_/utility.hpp, test/ft/state_machine.cpp
* on_entry and on_exit
* boolean operators for guards !, &&, and ||
* multiple actions
* orthogonal states
* submachines
* replace "terminate" state with plantuml termination syntax [*]
* update example to show these changes + use functor style instead of lambda style so the generated plantuml reads nicer
I strongly suspect this PR will get rejected because it uses C++17 instead of C++14. However, the improvements to plantuml generation are substantial. Is there a way this example could be included for those who use C++17 or could help be provided in removing the reliance on `if constexpr`?
Thank you.
=> Improving plantuml generation to support:

doc/overview.md
gurad2 -> guard2
[_On this page_](https://boost-ext.github.io/sml/overview.html)
```c++
const auto guard2 = [] -> bool { return true; }
state<class a> + event<e> [ guard2 ] / [](const auto& event) -> void {}  // Ok on all supported compilers
```
```c++
const auto guard2 = [] -> bool { return true; }
state<class a> + event<e> [ gurad2 ] / [](const auto& event) -> void {}  // Ok on all supported compilers
/* gurad2, not guard2! */
```
1. Open official docs.
2. Open _Overview_ section.
3. Scroll down to the _Supported/Tested compilers_ paragraph.
Issue: [#477](https://github.com/boost-ext/sml/issues/477)
=> Fix text error in docs.

doc/tutorial.md
The missing code block starting triple backquotes made the page to render improperly.
Problem:
- missing opening ` ```cpp ` 
Solution:
- adding it
=> [doc] fix markdown code block

doc/tutorial.md, include/boost/sml/utility/dispatch_table.hpp, test/ft/dispatch_table.cpp
Problem:
- The dispatch table (from `make_dispatch_table` did not return the result of `process_event` which it called
- This behavior was inconsistent with the User Guide which specifies that it should return something satisfying `callable<bool, (TEvent, int)>`
Solution:
- Change the return type of the table and `dispatch_event_impl::execute` to bool from void and to return `sm.process_event` 
Tests updated to check the return value at every step, which may be a bit excessive but verifies that it works in all the previous situations.
Also includes a minor update to docs
=> Dispatch Table Return Value

CMakeLists.txt
Boost libraries are only needed when building the benchmarks, exmaples
or tests, so only include boost libraries when either of those modules
are selected.
This will make the project behave well when being included using cmake
features like fetchcontent
Signed-off-by: Mikkel Jakobsen <mikkel.aunsbjerg@escolifesciences.com>
=> :wrench: [cmake] selectively include boost libraries

CMakeLists.txt, smlConfig.cmake.in
This commits aims to add support for including the library in other cmake-based projects using find_package().
Furthermore, this commit aligns the install target with the one generated by conan, i.e. sml::sml.
Based on the following guide:
https://dominikberner.ch/cmake-interface-lib/
Signed-off-by: Mikkel Jakobsen <mikkel.aunsbjerg@escolifesciences.com>
=> :wrench: [cmake] improve cmake install handling

CMakeLists.txt
When unconditionally setting target_compile_options like Werror and Wpedantic-errors, these compiler options are picked up by other projects that include sml using find_package. SML should not force the consumer libraries to use Werror.
Also add a minimum C++ version requirement for the target.
Signed-off-by: Mikkel Jakobsen <mikkel.aunsbjerg@escolifesciences.com>
=> :wrench: [cmake] do not propagate compile options to install targets

example/history.cpp
Problem:
- comments are wrong
Solution:
- fix the comments, see https://godbolt.org/z/1sjdbz17G to double-check
=> :wrench: [example] Fix comments of history example

doc/CHANGELOG.md
Problem:
- CHANGELOG.md link to 1.1.6 issues resolved doesn´t show any issue
Solution:
- Fix URL causing and empty time span for the filter (end date pointing to 2020 instead of 2022)
Issue: #
Reviewers:
@
=> fix typo on CHANGELOG.md date

.github/workflows/build_matrix.yml, .gitignore, CMakeLists.txt, example/eval.cpp, include/boost/sml.hpp, test/CMakeLists.txt, test/ft/state_machine.cpp, test/ft/transition_table.cpp, test/ft/transitions.cpp, test/ut/concepts.cpp, test/ut/type_traits.cpp, test/ut/utility.cpp
Problem:
* Lack of CI workflow for MSVC compiler.
* There are some compilation errors on MSVC.
Solution:
* Add workflow for MSVC with `CMAKE_CXX_COMPILER=cl` and `Generator=Ninja`
* cmake: Change cmake_minimum_required to 3.14 for leveraging CMAKE_CXX_COMPILER_FRONTEND_VARIANT to distinguish between *clang* and *clang-cl*.
* cmake: Use proper cxx compiler flags to check std version for MSVC/Clang-cl.
* cmake: Set cl options for Clang-cl
* eval.cpp: constexpr variable cannot have non-literal type in C++14.
* sml.hpp: Only check __cpp_noexcept_function_type since __cplusplus is not up-to-date on MSVC unless */Zc:__cplusplus* is specified.
* sml.hpp: Use __cpp_nontype_template_args >= 201911L to check whether class type non-type template parameter is supported or not.
* transitions.cpp: …
=> Add workflow for MSVC and fix compilation errors.

CMakeLists.txt, example/CMakeLists.txt, test/CMakeLists.txt, test/ft/CMakeLists.txt
Problem:
* We should not override CMAKE_CXX_STANDARD if it is defined by user.
* warning: unknown argument ignored in clang-cl: '-fexceptions' [-Wunknown-argument].
* Some build targets in example/CMakeLists.txt are not added by calling add_example().
Solution:
* If CMAKE_CXX_STANDARD is already defined, do not override it.
* Add IS_COMPILER_OPTION_MSVC_LIKE and IS_COMPILER_OPTION_GCC_LIKE vars to set the compiler flags. Fix warning: unknown argument ignored in clang-cl: '-fexceptions' [-Wunknown-argument].
* Use existing add_example() to add build targets.
Reviewers:
=> [cmake] clean up and fix warnings.

include/boost/sml.hpp, test/ft/policies_thread_safe.cpp
Problem:
Using `process(...)` within an event handler triggered from multiple threads in parallel causes a segfault, because the access to the root machine's `process_` queue was unprotected. The problem is illustrated in a new unit test.
Solution:
I moved the mutex lock from some very deep `process_event_impl` functions to the top-level `process_event`.
This solution also eliminates the need for a `recursive_mutex` when using `process`.
=> Fix thread safety

CMakeLists.txt
Problem:
INTERFACE target compile options apply to any target that includes sml with FetchContent or add_subdirectory.  This infects an entire project with -Werror, including third party libraries which may not be able to build with -Werror on.
Solution:
Disable these compile options if sml is not the top level project.
Issue: #517
Reviewers:
@
=> Prevent Werror infecting the rest of a project

test/ut/utility.cpp
Reviewing the unit tests to understand some issue I have seen, I found this cut-and-paste error: From the test name, I strongly guess, access to elements of `p2` should be tested (instead of `p`, which was already handled in test `pool_basic`).
=> Fix test pool_init_from_other_pool

include/boost/sml.hpp
Problem:
- In certain circumstances including `sml.hpp` on GCC performing `#pragma GCC diagnostic push` but not `#pragma GCC diagnostic pop`
Solution:
- Split previously-fused preprocessor check so `#pragma GCC diagnostic pop` doesn't require `__BOOST_SML_DEFINED_HAS_BUILTIN` to be defined
=> Always Diagnostic Pop on GCC

include/boost/sml.hpp, test/ft/dependencies.cpp
>Hello,
>I have fixed a bug in dependency resolution when requesting a "const T*" after injecting a "T*" as dependency.
>
> Before this fix, if a T* was injected as dependency, requesting a const T* will result in a invalid nullptr.
> The dependency resolution of objects passed by reference is not affected by this problem.
>
> I have added four tests:
>
> dependencies_with_reference
> dependencies_with_const_reference
> dependencies_with_pointer
> dependencies_with_const_pointer (this test fails without the fix)
> I am new to TMP and this is my first contribute in general so I hope I didn't do anything wrong.
I recently encountered this same issue, figured I'd resolve any merge conflicts so that it's able to be merged in.
=> Fix bug in dep resolution when requesting a "const T*"

example/defer_and_process.cpp, include/boost/sml.hpp, test/ft/actions_process.cpp, test/ft/actions_process_n_defer.cpp
Problem:
- Events added to the process queue silently fail when they are processed, but not handled
Solution:
- When processing events return both whether the initial event was handled and whether all processed events were handled
=> Report Process Queue Unhandled Events

include/boost/sml.hpp, test/ft/orthogonal_regions.cpp
Problem:
Since upgrading from 1.1.5 to 1.1.8, the code size of my project increased a lot. 
The cause seems to be the fix to the is(const TState &) function. 
This function was fixed in 1.1.6 to also work for orthogonal regions. 
Solution:
Created an overload with the pre 1.1.6 version of the function which is only selected when orthogonal regions equals 1. 
Also added some tests to make sure the right version is selected when regions is not 1.
Reviewers:
=> reduce code size for state machines without orthogonal regions

include/boost/sml.hpp, test/ft/states.cpp
Allowing a default reaction on events without having to add them to every state.
I believe a similar feature exists in sml2
Problem:
-Many (of my) state machines have events that are handled in (almost) all states. For example, transitions to an error state or a stop/abort event. Currently there is no way to express a default reaction to an event. 
Solution:
-Added an "any" state. The any state is written as "state<_>". Whenever an event is processed in a state that does NOT handle that event, the "any" state is checked. If the "any" state handles the event it is processed as if the current state is the "any" state. This change could break code that already uses "state<_>" as a normal state.  
Issue: #328 
Reviewers:
=> Added "any state" feature 

include/boost/sml.hpp, test/ft/CMakeLists.txt, test/ft/dont_instantiate_statemachine_class.cpp
Added dont_instantiate_statemachine_class policy: when supplied, don't subclass the transition table type and require a reference to an instance of that type in the constructor of sml::sm and all sub-statemachine types.
Problem:
-
A non-empty transition table class is always instantiated by boost::sml::sm.
This is because `sm_impl` is a subclass of the transition table class whenever the class is non-empty.
```c++
struct sm_impl : aux::conditional_t<aux::is_empty<typename TSM::sm>::value, aux::none_type, typename TSM::sm> {...}
```
When the transition table class has a non default constructor, it is required to supply a reference to an instance of this class in the constructor of `boost::sml::sm`.
This leads to confusion, when a reference to the instance of a transition table is supplied …
=> Added policy that controls if the transition table class is instantiated

test/ft/CMakeLists.txt, test/ft/policies_logging.cpp
Problem:
- 
While testing some logging behaviors, I noticed that the tests for logging were disabled in cmake.
The tests did not correctly handle the current implementation of `sml_impl::start` (`sml.hpp`, line 1501).
```c++
template <class TDeps, class TSubs>
constexpr void start(TDeps &deps, TSubs &subs) {
process_event(on_entry<_, initial>{}, deps, subs);
}
```
This code causes the sm to process the initial `on_entry` event, which then correctly invokes the logger for that event.
However, the test file `policies_logging.cpp` did not consider the log message of that initial entry event and therefore failed. 
Solution:
-
- added log messages of the initial on_entry event to the vector of expected message
- re-enabled the tests in cmake
=> Adapted policies_logging.cpp tests to correctly handle statemachine start

include/boost/sml.hpp, test/ft/actions_defer.cpp, test/ft/actions_process.cpp, test/ft/actions_process_n_defer.cpp, test/ft/static_deque.h, test/ft/static_queue.h
Problem:
-
All examples for `sml::process_queue` and `sml::defer_queue` are based on `std::queue`.
While this approach is fine for desktop c++, some use cases exist where dynamic allocations are not allowed / desired.
Some examples are:
- embedded systems (no dynamic memory allocations available)
- real-time systems with pre-allocated objects
As boost::sml is a library that targets embedded systems, it should allow the use of pre-allocated queues.
Solution:
-
I enabled the use of pre-allocated queues by making `queue_event` default constructible.
This allows storing instances of `queue_event` in a container that pre-allocates all elements upon construction (e.g.
`std::array`).
I added additional tests in `actions_process.cpp`, `actions_defer.cpp` and `actions_process_n_defer.cpp` that
use …
=> allow the usage of "static queues" (based on std::array) for process_queue and defer_queue

include/boost/sml.hpp
Problem:
- Library cannot be used with IAR compiler
Solution:
- Add compiler specific switches
Reviewers:
=> Add support for IAR arm compiler

include/boost/sml.hpp, test/ft/states.cpp
Problem:
- Any state does not work if there is a nested state machine within a state machine with any state, as demonstrated in the failing test `any_state_nested`.
Solution:
- Modified the `get_state_mapping` specialization for nested state machines to consider both direct state transitions and any state transitions.
- The implementation now tries direct transitions first, and if those don't handle the event, it falls back to any state transitions.
- This ensures consistent behavior between regular states and nested state machines when using the `any` state.
Issue: #622
Reviewers:
@kris-jusiak
=> Handling the `any` state correctly when using a nested state machine

include/boost/sml.hpp, test/ft/transitions.cpp
Problem:
- Anonymous transitions in terminated sub statemachines only propagate to the parent if the sub statemachine is the initial state.
Solution:
- Process events to the sub statemachine if it's not terminated.
Issue: #626
Reviewers:
@kris-jusiak
=> Anonymous transitions in composition

CMakeLists.txt
Compile options added to INTERFACE libraries propagate to any target that includes SML with either FetchContent or add_subdirectory.  Add these compile options only when SML is the top level project.
=> Prevent compiler options propagating to projects using SML
