include/boost/sml.hpp
include/boost/sml/front/actions/defer.hpp

Fixed move construction algorithm on type erased defer_event.

Fixed #91.

---

tutorial/index.html

Must "not return" means something quite different.

Update tutorial text

---

test/ft/dependencies.cpp

Problem:
- Theare are no tests veryfing whether a smart ptrs can be used.
Solution:
- Extend dependencies feature tests.

:white_check_mark: Verify dependencies and smart pointers

---

doc/cppcon-2018/index.html

Problem:
- Suggested by Timur changes haven't been applied.
Solution:
- Apply them.

:books: [CppCon-2018] Review updates

---

doc/cppcon-2018/index.html

Problem:
- Policies were missing N parameter.
Solution:
- Add it.

:books: [CppCon-2018] Fixes for policies

---

benchmark/connection/stl_coroutine_fun_variant.cpp
benchmark/connection/stl_coroutine_goto.cpp
benchmark/connection/stl_coroutine_loop.cpp
doc/cppcon-2018/index.html

Problem:
- There are some slides issues noticed during the talk.
Solution:
- Fix the typos.

:books: [CppCon-2018] Final slide fixes

---

include/boost/sml.hpp
include/boost/sml/back/state_machine.hpp
test/ft/policies_testing.cpp

fix set_current_states for composite states

---

CMakeLists.txt
benchmark/complex/CMakeLists.txt
benchmark/composite/CMakeLists.txt
benchmark/header/CMakeLists.txt
benchmark/simple/CMakeLists.txt
doc/embo-2017/example/CMakeLists.txt
example/CMakeLists.txt
test/unit/CMakeLists.txt

This is a fix for #244 
Frankly speaking I' not sure if it is a correct way to set the include directories for all sub-projects.

add include_directories to use it in all subprojects

---

include/boost/sml.hpp
include/boost/sml/back/state_machine.hpp
test/ft/state_machine.cpp

* Fix the broken move constructor #247 
* remove all copy/move constructors and let the compiler figure it out on its own

Fix state machine move constructor

---

include/boost/sml.hpp
include/boost/sml/back/queue_handler.hpp
test/ft/actions_defer.cpp

Addresses issue described in https://github.com/boost-experimental/sml/issues/279

Implement queue_event move assignment via static move/dtor_impl

---

README.md
doc/CHANGELOG.md

Problem:
- There are a lot bugs fixed.
- Additional compiler support.
Solution:
- Release a SML version `1.1.1` to reflect the above changes.

:arrow_up: [SML] Version `1.1.1`

---

.github/workflows/pph-checker.yml

Adds a github action which runs the pph script and checks if this introduces changes.

feat: Add pph checker

---

.mkdocs.yml
doc/CHANGELOG.md
doc/index.md
include/boost/sml.hpp

Problem:
- Support of GCC >= 10 has been fixed.
Solution:
- Update the minor version to `1.1.2`

:arrow_up: [SML] Version `1.1.2`

---

README.md
doc/index.md

Problem:
- There are new videos available.
Solution:
- Add them to the spec.

:books: [doc] Add new video materials

---

example/data.cpp

Problem:
- There is no example how to make data per state.
Solution:
- Extend data example to show how to make states with data.

:art: :new: [example] Per state data

---

test/ft/transitions.cpp

Problem:
- No tests for member functions as actions and guards
Solution:
- Add a test

Add a test for using member functions as actions and guards

---

include/boost/sml.hpp
include/boost/sml/aux_/type_traits.hpp

Problem:
- conditional is memoized on bool and types.
Solution:
- Introduce conditional memoized on bool only and use an alias for types.

:racehorse: [type_traits] Faster to compile version of `conditional`

---

example/plant_uml.cpp

Allows to build on ubuntu 18.04 with GCC 7.5
Problem:
- The plant_uml example does not build on Ubuntu 18.04 with GCC 7.5 with the error message:
```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/projects/sml/build
[  2%] Building CXX object example/CMakeFiles/transitions.dir/transitions.cpp.o
[  4%] Linking CXX executable transitions
[  4%] Built target transitions
[  6%] Building CXX object example/CMakeFiles/testing.dir/testing.cpp.o
[  8%] Linking CXX executable testing
[  8%] Built target testing
[ 10%] Building CXX object example/CMakeFiles/plant_uml.dir/plant_uml.cpp.o
/home/user/projects/sml/example/plant_uml.cpp: In substitution of ‘template<int N, class ... Ts> using NthTypeOf = typename std::tuple_element<N, std::tuple<Ts ...> >::type …
```

Add tuple include in the plant_uml example

---

example/plant_uml.cpp

Problem:
- The plant_uml example only dump the plant_uml text to `stdout` but it can be convenient to reuse the same code to dump into a `std::stringstream` for example.
Solution:
- Take a `std::ostream&` as argument in the `dump()` function.
Issue: #493 (partially)
Reviewers:

plant_uml example: take an std::ostream& to dump to any stream

---

include/boost/sml.hpp
test/ft/actions_defer.cpp

Problem:
I believe there are a few problems with the current defer implementation. 
According to [this](https://en.wikipedia.org/wiki/UML_state_machine#Event_deferral) the defer queue should only be processed when a new state is entered. 
Currently the defer queue is processed every time an event is handled. 
This causes problems when the defer is combined with a guard or action.
Solution:
I attempted to check the defer queue only after a state change. 
The check is only performed on the current state of the first region. 
Therefore it is probably broken for state machines with orthogonal regions. 
My solution also break the "defer_reaction" test. 
If the test accurately describes how the sml::back::defer is supposed to work, then what is the difference with sml::back::process. 
Issue: …

fix for defer combined with action and multiple defers

---

include/boost/sml.hpp

@krzysztof-jusiak it would be great if we can have a v1.1.10 release also

more constexpr
